knpu_oauth2_client:
    clients:
        entra:
            type: microsoft
            client_id: "%env(OAUTH_ENTRA_CLIENT_ID)%"
            client_secret: "%env(OAUTH_ENTRA_CLIENT_SECRET)%"
            redirect_route: connect_entra_check
            redirect_params: {}
            url_authorize: "%env(OAUTH_ENTRA_URL_AUTHORIZE)%"
            url_access_token: "%env(OAUTH_ENTRA_URL_ACCESS_TOKEN)%"
