services:

  App\Entity\Repository\UserRepository:
    class: App\Entity\User
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - App\Entity\User

  App\Entity\Repository\ReportRepository:
    class: App\Entity\Report\Report
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - App\Entity\Report\Report
    calls:
      - [setSearchFilter, ["@App\\Service\\Search\\ClientSearchFilter"]]

  App\Entity\Repository\ClientRepository:
    class: App\Entity\Client
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - App\Entity\Client
    calls:
      - [setSearchFilter, ["@App\\Service\\Search\\ClientSearchFilter"]]

  App\Entity\Repository\OrganisationRepository:
    class: App\Entity\Organisation
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - App\Entity\Organisation

  App\Entity\Repository\NamedDeputyRepository:
    class: App\Entity\NamedDeputy
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - App\Entity\NamedDeputy

  App\Entity\Repository\CasRecRepository:
    class: App\Entity\CasRec
    factory: ["@doctrine.orm.entity_manager", getRepository]
    arguments:
      - App\Entity\CasRec

  App\Entity\Ndr\NdrRepository:
      class: App\Entity\Ndr\Ndr
      factory: ["@doctrine.orm.entity_manager", getRepository]
      arguments:
          - App\Entity\Ndr\Ndr

  App\Entity\Repository\UserResearchResponseRepository:
      class: App\Entity\UserResearch\UserResearchResponse
      factory: [ "@doctrine.orm.entity_manager", getRepository ]
      arguments:
          - App\Entity\UserResearch\UserResearchResponse
