[template]
src  = "xdebug.ini.tmpl"
dest = "/usr/local/etc/php/conf.d/xdebug.ini"
keys = [
    "/opg/php/xdebug/enabled",
    "/opg/php/xdebug/remote/port",
    "/opg/php/xdebug/remote/host",
    "/opg/php/xdebug/idekey"
]
