#imports:
#    - { resource: parameters.yml }
#    - { resource: security.yml }
#    - { resource: services.yml }
#
#services:
#    # Logtash formatter for Kibana
#    logstash_formatter:
#        class: Monolog\Formatter\LogstashFormatter
#        arguments: [ "application.client", null, null, "", 1 ]
#    line_formatter:
#        class: Monolog\Formatter\LineFormatter
