services:
    Alphagov\Notifications\Client:
        alias: App\Service\Mailer\NotifyClientMock

    App\Service\Mailer\NotifyClientMock:
        class: App\Service\Mailer\NotifyClientMock
        arguments:
            $config:
                httpClient: '@Http\Adapter\Guzzle6\Client'
                apiKey: '%env(NOTIFY_API_KEY)%'
            $logger: '@logger'
