imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname:   digideps_unit_test
        
services:
    attemptsInTimeChecker:
        class:  AppBundle\Service\BruteForce\AttemptsInTimeChecker
        arguments: [ @snc_redis.default ]
        calls:
            - [ setRedisPrefix, ["test_ac_ret_code"] ]
            # after 5 attempts in the last 10 minutes, return a different return code (activate captcha)
            - [ addTrigger, [  5, 600 ] ]
    attemptsIncrementalWaitingChecker:
        class:  AppBundle\Service\BruteForce\AttemptsIncrementalWaitingChecker
        arguments: [ @snc_redis.default ]
        calls:
            - [ setRedisPrefix, ["test_ac_exception"] ]
            # after 10 attempts, freeze for 10 minutes. used by AuthControllerTest::testBruteForceSameEmail
            - [ addFreezingRule, [  10, 600 ] ]

# during tests, display on the console the entries with priority greater than "warnings" level
monolog:
   handlers:
       main:
           type: stream
           level: warning
           
jms_serializer:
    metadata:
        cache: none
        cache: file
        debug: true
        
parameters:
    fixtures:
        deputy@example.org:
            firstname: test
            lastname: deputy
            roleId: 2
            password: Abcd1234
        
        admin@example.org:
            firstname: test
            lastname: admin
            roleId: 1
            password: Abcd1234

        pa@example.org:
            firstname: test
            lastname: pa
            roleId: 6
            password: Abcd1234

        pa_admin@example.org:
            firstname: test
            lastname: pa-admin
            roleId: 7
            password: Abcd1234

        pa_team_member@example.org:
            firstname: test
            lastname: pa-team-member
            roleId: 8
            password: Abcd1234