imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

assetic:
    use_controller: false
    
twig:
    cache:  false
security:
    firewalls:
        dev:
            pattern:  ^/
            security: false
services:
    mail_sender:
        class: AppBundle\Service\Mailer\MailSenderMock
        arguments: [ @service_container ]
    mailer.transport.smtp.default:
        class: AppBundle\Service\Mailer\Transport\TransportMock
    mailer.transport.smtp.secure:
        class: AppBundle\Service\Mailer\Transport\TransportMock
