imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    ide: 'phpstorm://open?file=%%f&line=%%l'

web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: true

services:
    data_collector.apiCollectorss:
        class: AppBundle\Service\ApiCollector
        arguments: ["@rest_client"]
        tags:
            - { name: data_collector, template: "AppBundle:Manage:api-collector", id: "api-collector" }

monolog:
   handlers:
       main:
           formatter: line_formatter
           channels: [ "!translation" ]

jms_serializer:
    metadata:
        cache: none
        cache: file
        debug: true 