app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

app_v2:
    resource: "@AppBundle/v2/Controller/"
    type:     annotation
    prefix:   /v2

app_v2_registration:
    resource: "@AppBundle/v2/Registration/Controller/"
    type:     annotation
    prefix:   /v2
