services:
    kernel.listener.responseConverter:
        class: AppBundle\EventListener\RestInputOuputFormatter
        arguments: [ "@serializer", "@logger", ["json"], "json", "%kernel.debug%" ]
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }            
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }      
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }      
    em:
        alias: doctrine.orm.entity_manager

    doctrine.listener:
        class: AppBundle\EventListener\DoctrineListener
        tags:
            - { name: doctrine.event_listener, event: prePersist, method: prePersist }
            - { name: doctrine.event_listener, event: preRemove, method: preRemove }
    user_registration_service:
        class: AppBundle\Service\UserRegistrationService
        arguments: [ "@em" ]

    opg_digideps.user_service:
        class: AppBundle\Service\UserService
        arguments:
          - "@opg_digideps.user_repository"
          - "@opg_digideps.team_repository"
          - "@em"

    monolog.processor.add_request_id:
        class: AppBundle\Service\RequestIdLoggerProcessor
        arguments:  [ "@service_container" ]
        tags:
              - { name: monolog.processor, method: processRecord }

    stats_service:
        class: AppBundle\Service\StatsService
        arguments: [ "@em" ]

    opg_digideps.report_service:
        class: AppBundle\Service\ReportService
        arguments:
          - "@opg_digideps.report_repository"
          - "@opg_digideps.casrec_repository"
          - "@em"

    opg_digideps.report_repository:
        class: AppBundle\Entity\Repository\ReportRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
         - AppBundle\Entity\Report\Report

    opg_digideps.casrec_repository:
        class: AppBundle\Entity\Repository\CasRecRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
         - AppBundle\Entity\CasRec

    opg_digideps.user_repository:
        class: AppBundle\Entity\Repository\UserRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
         - AppBundle\Entity\User

    opg_digideps.team_repository:
        class: AppBundle\Entity\Repository\TeamRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
         - AppBundle\Entity\Team

    gedmo.listener.softdeleteable:
      class: Gedmo\SoftDeleteable\SoftDeleteableListener
      tags:
        - { name: doctrine.event_subscriber, connection: default }
      calls:
        - [ setAnnotationReader, [ @annotation_reader ] ]
