imports:
    - { resource: services_mail.yml }
    - { resource: services_forms.yml }
    - { resource: services_twig.yml }
    - { resource: services_api.yml }
    - { resource: services_listeners.yml }
    - { resource: services_login.yml }

services:
    redirector_service:
        class: AppBundle\Service\Redirector
        arguments: [ "@security.context", "@router", "@session", "%env%" ]

    wkhtmltopdf:
        class: AppBundle\Service\WkHtmlToPdfGenerator
        arguments:  
           url: "http://wkhtmltopdf:80"
           timeoutSeconds: 30

    step_redirector:
      class: AppBundle\Service\StepRedirector
      arguments: [ "@router" ]

    report_validator:
      class: AppBundle\Service\ReportValidator
      arguments: [ "@request_stack"]
