services:
    kernel.listener.session_listener:
        class: AppBundle\EventListener\SessionListener
        arguments: [ "@router" , "@logger", {idleTimeout: "%session_expire_seconds%"}]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    logout_listener:
      class:   AppBundle\EventListener\LogoutListener
      arguments:  ["@security.context", "@rest_client", "@router"]

    response_nocache_listener:
       class:   AppBundle\EventListener\ResponseNoCacheListener
       tags:
              - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    kernel.listener.auth_token_expired_listener:
        class: AppBundle\EventListener\AuthTokenExpiredListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    monolog.processor.add_request_id:
        class: AppBundle\Service\RequestIdLoggerProcessor
        arguments:  [ "@service_container" ]
        tags:
            - { name: monolog.processor, method: processRecord }


    kernel.listener.login_listener:
        class: AppBundle\EventListener\LoginEventListener
        arguments: [ "@event_dispatcher", "@redirector_service" ]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

