[template]
src = "parameters.yml.tmpl"
dest = "/var/www/config/parameters.yml"
keys = [
    "/opg/docker/tag",
    "/role",
    "/session",
    "/ga",
    "/secret",
    "/api",
    "/fixtures",
    "/admin",
    "/nonadmin",
    "/mock",
    "/email",
    "/smtp",
    "/s3/bucketname",
    "/s3/localstack",
    "/filescanner/url",
    "/filescanner/sslverify",
    "/wkhtmltopdf/address"
 ]
