parameters:
  bad_pdf_keywords:
    - 'AcroForm'
    - 'JavaScript'
    - 'Launch'
    - 'RichMedia'
    - 'XFA'

services:
  Aws\S3\S3Client:
    arguments: ["%s3_client_params%"]

  AppBundle\Service\File\Storage\S3Storage:
    arguments: [ '@Aws\S3\S3Client', "%s3_bucket_name%", "@logger" ]

  guzzle_file_scanner_client:
    class: GuzzleHttp\Client
    public: true
    arguments:
      $config:
        base_uri: "%file_scanner_url%"
        verify: "%file_scanner_sslverify%"
        proxy: ""
        debug: false
        headers:
          Content-Type: multipart-form-data
        version: "1.1"

        timeout: 10
        allow_redirects: false

  AppBundle\Service\File\Verifier\MultiFileFormUploadVerifier:
    calls:
      - [ addVerifier, ['@AppBundle\Service\File\Verifier\ConstraintVerifier'] ]
      - [ addVerifier, ['@AppBundle\Service\File\Verifier\ScannerVerifier'] ]

  AppBundle\Service\File\Scanner\ClamFileScanner:
    arguments: [ "@guzzle_file_scanner_client", "@logger", "%bad_pdf_keywords%"]

  guzzle_pdf_generator_client:
    class: GuzzleHttp\Client
    public: true
    arguments:
      $config:
        base_uri: 'http://wkhtmltopdf'
        proxy: ""
        debug: false
        headers:
          Content-Type: application/json
        version: "1.1"

        timeout: 10
        allow_redirects: false
