[template]
src = "parameters.yml.tmpl"
dest = "/app/app/config/parameters.yml"
keys = [
    "/opg/docker/tag",
    "/frontend/role",
    "/frontend/session",
    "/frontend/ga",
    "/frontend/secret",
    "/frontend/api",
    "/frontend/fixtures",
    "/frontend/admin",
    "/frontend/nonadmin",
    "/frontend/behat",
    "/frontend/email",
    "/frontend/smtp",
    "/frontend/url"
 ]
