app:
    resource: "../../src/Controller/"
    type: annotation
    prefix: /

app_v2:
    resource: "../../src/v2/Controller/"
    type: annotation
    prefix: /v2

app_v2_registration:
    resource: "../../src/v2/Registration/Controller/"
    type: annotation
    prefix: /v2

app_v2_fixture:
    resource: "../../src/v2/Fixture/Controller/"
    type: annotation
    prefix: /v2

app_v2_tools:
    resource: "../../src/v2/Tools/Controller/"
    type: annotation
    prefix: /v2

kernel:
    resource: ../../src/Kernel.php
    type: annotation
