version: "3.2"

services:
  pythontests:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      PYTHONPATH: /workdir
    restart: always
  postgres:
    image: postgres:13.11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: api
      PGDATA: /var/lib/postgresql96/data
    restart: always
    networks:
      default:
        aliases:
          - local.postgres
