services:
    AppBundle\Form\Report\Asset\AssetTypeTitle:
        arguments: ["%asset_dropdown%", "@translator", "report-assets"]
        tags:
            - { name: form.type }

    AppBundle\Form\Ndr\Asset\AssetTypeTitle:
        arguments: ["%asset_dropdown%", "@translator", "ndr-assets"]
        tags:
            - { name: form.type }

    AppBundle\Form\FeedbackReportType:
        calls:
            - [ setTranslator, ["@translator"] ]
        tags:
            - { name: form.type }

    AppBundle\Form\FeedbackType:
        calls:
            - [ setTranslator, ["@translator"] ]
        tags:
            - { name: form.type }

    AppBundle\Validator\Constraints\EmailSameDomainValidator:
        calls:
            - [ setTokenStorage, ["@security.token_storage"] ]
        tags:
            - { name: validator.constraint_validator, alias: email_same_domain }
