services:
    security.validator.d_user_password:
        class: AppBundle\Validator\Constraints\DUserPasswordValidator
        arguments: [ "@security.token_storage", "@rest_client" ]
        tags:
            - { name: validator.constraint_validator, alias: security.validator.d_user_password }

    AppBundle\Service\Client\TokenStorage\RedisStorage:
        arguments: ["@snc_redis.default", "redis_token_storage_dd"]

    deputy_provider:
        alias: AppBundle\Service\DeputyProvider
