services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\Service\Mailer\MailFactory:
        public: true
        arguments:
            $emailParams: "%email_params%"
            $baseURLs:
                front: '%env(NONADMIN_HOST)%'
                admin: '%env(ADMIN_HOST)%'

    AppBundle\Service\Mailer\MailSenderInterface: '@AppBundle\Service\Mailer\MailSender'

    Alphagov\Notifications\Client:
        class: Alphagov\Notifications\Client
        arguments:
            $config:
                httpClient: '@Http\Adapter\Guzzle6\Client'
                apiKey: '%env(NOTIFY_API_KEY)%'

    AppBundle\Service\Mailer\NotifyClientMock:
        arguments:
            $config:
                httpClient: '@Http\Adapter\Guzzle6\Client'
                apiKey: '%env(NOTIFY_API_KEY)%'
            $logger: '@logger'

    Http\Adapter\Guzzle6\Client:
        class: Http\Adapter\Guzzle6\Client
