name: "[Security] Secret Scan on Push"

on: workflow_call

permissions:
  id-token: write
  contents: read

jobs:
  secret_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Trivy Secret Scan
        id: trivy_secret_scan
        uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # v0.32.0
        with:
          scan-type: fs
          scanners: secret
          exit-code: 1
          format: table
          timeout: 5m

  slack_notify_secret_scan_failure:
    name: notify of secret-scan failure
    uses: ./.github/workflows/_slack-notification.yml
    if: ${{ failure() }}
    needs: secret_scan
    with:
      success: no
      branch: ${{ github.ref_name }}
      account: ${{ vars.DEVELOPMENT_ACCOUNT }}
      failure_reason: "Secret Found In PR"
